.PHONY: all clean clean_image

# This Makefile is driven by the justfile; most variables come in via env.
# Targets with a leading "." are sentinel files that track whether a stage has
# completed successfully, so reruns skip already-finished work.

RELEASE ?= trixie
ROOT_PW ?= 0000
USER_LOGIN ?= kalm
USER_PW ?= 0000
HOSTNAME ?= fold
# kmscon isn't in trixie, so we fetch the arm64 .deb out of the Debian archive.
# The plain pool path (ftp.*/debian/pool/...) gets purged once a package is
# superseded, so we use snapshot.debian.org's permanent content-addressed
# /file/<sha1> URL and verify the download against KMSCON_SHA256, so a
# wrong/corrupt fetch fails the build instead of installing a surprise kmscon.
# The pin is (re)generated by `just update_snapshot` into rootfs/kmscon.env,
# included here; the ?= values are the committed fallback so a fresh checkout
# still builds if that file is absent.
-include rootfs/kmscon.env
KMSCON_URL ?= https://snapshot.debian.org/file/19dae225043718dfcbf02b50a7fcbedbfe4ab262
KMSCON_SHA256 ?= 5a200898513a82cac4f9262f7c20fe4b2bfc6d1d57045ab5f7d9ee0b9ca07a4f
# felix's super partition is 2082816 × 4096B = 8136.9 MiB; 8100M leaves a small
# margin so fastboot doesn't reject on a slightly-oversized image.
SIZE ?= 8100M
SYSROOT_DIR ?= rootfs/sysroot
KERNEL_SOURCE_DIR ?= kernel/source
KERNEL_BUILD_DIR ?= $(KERNEL_SOURCE_DIR)/out/felix/dist
APT_PACKAGES_FILE ?= rootfs/packages.txt
MODULE_ORDER_PATH ?= rootfs/module_order.txt
ROOTFS_IMG ?= boot/rootfs.img
MKBOOTIMG ?= tools/mkbootimg/mkbootimg.py
BAZEL ?= kernel/source/tools/bazel
OVERLAY_DIR ?= rootfs/overlay
VENDOR_FIRMWARE_STAGE ?= rootfs/vendor-firmware/extracted

OVERLAY_FILES := $(shell find $(OVERLAY_DIR) -type f 2>/dev/null)

# Debian archive pin. rootfs/debian_snapshot holds a snapshot.debian.org
# timestamp (managed by `just update_snapshot`); pinning the mirror is what
# makes a given IMAGE_VERSION reproducible. An empty pin leaves MIRROR empty,
# so debootstrap falls back to its default (live) mirror — a fresh checkout
# without a pin still builds.
SNAPSHOT ?= $(shell cat rootfs/debian_snapshot 2>/dev/null)
MIRROR ?= $(if $(SNAPSHOT),https://snapshot.debian.org/archive/debian/$(SNAPSHOT)/,)

# Image version string for /etc/os-release + the login banner. version.txt holds
# the human-bumped number (managed by release-please); the git short hash (and
# -dirty marker) pin it to a build. BUILD_DATE is informational — the snapshot
# pin above is the actual reproducibility anchor, not the build date.
IMAGE_BASE_VERSION := $(shell cat version.txt 2>/dev/null || echo 0.0.0)
GIT_REV := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
GIT_DIRTY := $(shell test -n "$$(git status --porcelain 2>/dev/null)" && echo -dirty)
IMAGE_VERSION ?= $(IMAGE_BASE_VERSION)-g$(GIT_REV)$(GIT_DIRTY)
BUILD_DATE ?= $(shell date -u +%Y-%m-%d)

# Wrap nspawn invocations through tools/nspawn-wrap.sh so each one starts
# from a known-good sysroot/dev (no leftover mounts, no stale /dev/pts).
# See the script header for the systemd >= 260 specifics that motivate it.
# Trailing `--` separates the wrapper's sysroot arg from the nspawn argv.
NSPAWN_WRAP := sudo tools/nspawn-wrap.sh $(SYSROOT_DIR) --
# --resolv-conf=bind-host overrides the container's /etc/resolv.conf for the
# lifetime of the nspawn session. Packages.txt installs systemd-resolved,
# whose postinst points /etc/resolv.conf at a stub that only resolves when
# systemd-resolved is running (it isn't, under nspawn). Without this flag,
# any nspawn call after that postinst loses DNS, including reruns.
NSPAWN := $(NSPAWN_WRAP) --resolv-conf=bind-host

# Running `make` directly bypasses the env vars set by the justfile (notably
# KERNEL_VERSION, which is read from kernel/kernel_version). Always go through
# `just all` so those are in scope.
all:
	@echo "Use 'just all' instead so KERNEL_VERSION and friends are exported."
	@just --list

.create_image:
	mkdir -p $(SYSROOT_DIR)
	# Use truncate (sparse file), not fallocate: the build host's root fs (ext2) returns
	# "fallocate: Operation not supported". A sparse image is fine for mkfs.ext4 + fastboot.
	sudo truncate -s $(SIZE) $(ROOTFS_IMG)
	sudo mkfs.ext4 -F -L rootfs $(ROOTFS_IMG)
	touch $@

.debootstrap: .create_image
	just mount_rootfs
	# Trailing $(MIRROR) pins the archive to the snapshot.debian.org timestamp
	# in rootfs/debian_snapshot; empty MIRROR => debootstrap's default mirror.
	sudo debootstrap --variant=minbase --include=symlinks --arch=arm64 --foreign $(RELEASE) $(SYSROOT_DIR) $(MIRROR)
	# nixpkgs heavily patches debootstrap: both the shebang AND in-script
	# references to dpkg/chroot/unshare are rewritten to absolute /nix/store
	# paths. --foreign copies the host script verbatim into sysroot, so
	# inside the nspawn container those paths don't exist and the script
	# either fails to exec or silently dies on `set -e` when the first
	# nix-store binary is invoked. Rewrite both:
	#   - line 1 (shebang): /nix/store/<hash>/bin/bash → /bin/bash
	#   - lines 2..: strip /nix/store/<hash>/bin/ entirely so PATH lookup
	#     resolves the (container's own) dpkg, chroot (/usr/sbin), unshare.
	# No-op on non-Nix hosts (the upstream debootstrap has no /nix/store
	# references at all).
	sudo sed -i \
		-e '1s|^#!/nix/store/[^/]*/bin/|#!/bin/|' \
		-e '2,$$s|/nix/store/[^/]*/bin/||g' \
		$(SYSROOT_DIR)/debootstrap/debootstrap
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) debootstrap/debootstrap --second-stage
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) symlinks -cr .
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) sh -c "echo root:$(ROOT_PW) | chpasswd"
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) sh -c "echo $(HOSTNAME) > /etc/hostname"
	just unmount_rootfs
	touch $@

# Must build inside the flake's FHS shell so kleaf's host tools (python3, perl, bash,
# rsync) resolve and Bazel's server starts in the FHS mount namespace:
#   nix run .#bazel-fhs -- -c 'just build_kernel'
# --config=local is kleaf's "reduce sandboxes" mode (build/kernel/kleaf/docs/sandbox.md):
# it runs the in-tree kernel_build/kernel_config actions locally (per-target cache dirs)
# while keeping modules_install/dtbo/uapi/abi actions sandboxed. This is what makes
# --config=use_source_tree_aosp (in-tree GKI build) work on NixOS. Do NOT replace it with
# a blanket --spawn_strategy=local: that forces the sandbox-required actions to run local
# and they abort with "FATAL: this action must be executed in a sandbox!".
# NOTE: per the kleaf docs, run `tools/bazel clean` if you change --strategy/--config,
# else stale cached action outputs cause confusing failures.
.build_kernel: kernel/custom_defconfig_mod/BUILD.bazel kernel/custom_defconfig_mod/custom_defconfig
	cd $(KERNEL_SOURCE_DIR); $(BAZEL) run \
		--config=use_source_tree_aosp \
		--config=stamp \
		--config=felix \
		--config=local \
		--defconfig_fragment=//custom_defconfig_mod:custom_defconfig \
		//private/devices/google/felix:gs201_felix_dist
	@echo "Updating kernel version string"
	strings $(KERNEL_BUILD_DIR)/Image | grep "Linux version" | head -n 1 | awk '{print $$3}' > kernel/kernel_version
	touch $@

.sync_vendor_firmware:
	just sync_vendor_firmware
	touch $@

.install_vendor_firmware: .debootstrap .sync_vendor_firmware
	just mount_rootfs
	sudo mkdir -p $(SYSROOT_DIR)/vendor/firmware
	sudo rsync -a $(VENDOR_FIRMWARE_STAGE)/firmware/ $(SYSROOT_DIR)/vendor/firmware/
	just unmount_rootfs
	touch $@

.install_packages: .debootstrap $(APT_PACKAGES_FILE) $(OVERLAY_FILES) version.txt
	just mount_rootfs
	# apt tuning for the snapshot.debian.org mirror (all harmless on the live
	# mirror, so written unconditionally):
	#   Check-Valid-Until false  - snapshot Release files carry an old
	#                              Valid-Until; apt rejects them as expired.
	#   Retries 5                - snapshot intermittently freezes a connection
	#     + *::Timeout 60          mid-transfer; without a timeout apt hangs
	#                              forever, so cap it and retry instead.
	#   Pipeline-Depth 0         - snapshot throttles/stalls under apt's default
	#                              HTTP pipelining; disable it.
	# Regular file, no symlink — safe to write host-side into the mounted sysroot.
	sudo sh -c "printf '%s\n' \
		'Acquire::Check-Valid-Until \"false\";' \
		'Acquire::Retries \"5\";' \
		'Acquire::http::Timeout \"60\";' \
		'Acquire::https::Timeout \"60\";' \
		'Acquire::http::Pipeline-Depth \"0\";' \
		> $(SYSROOT_DIR)/etc/apt/apt.conf.d/99snapshot"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c "apt-get update"
	# Locale setup.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"DEBIAN_FRONTEND=noninteractive apt-get -y install locales apt-utils"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"export DEBIAN_FRONTEND=noninteractive; \
		sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
		&& dpkg-reconfigure locales \
		&& update-locale en_US.UTF-8"
	# Pre-stage the pinned kmscon .deb (trixie dropped the package) so the
	# single apt-get install below resolves its deps alongside packages.txt.
	sudo curl -L --fail -o $(SYSROOT_DIR)/var/cache/apt/archives/kmscon.deb "$(KMSCON_URL)"
	# Fail loudly if the fetched .deb isn't the pinned one.
	echo "$(KMSCON_SHA256)  $(SYSROOT_DIR)/var/cache/apt/archives/kmscon.deb" | sha256sum -c -
	# Packages from rootfs/packages.txt plus the staged kmscon .deb.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"DEBIAN_FRONTEND=noninteractive apt-get -y install $(APT_PACKAGES) /var/cache/apt/archives/kmscon.deb"
	# Unprivileged user with passwordless sudo. Paired with the autologin
	# override in rootfs/overlay/etc/systemd/system/kmsconvt@.service.d/.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"id -u $(USER_LOGIN) >/dev/null 2>&1 || useradd -m -s /bin/bash -G sudo $(USER_LOGIN)"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"echo $(USER_LOGIN):$(USER_PW) | chpasswd"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"echo '%sudo ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/99-sudo-nopasswd \
		&& chmod 0440 /etc/sudoers.d/99-sudo-nopasswd"
	# Explicitly enable a getty on felix's UART console. The compiled-in
	# `console=ttynull` in CONFIG_CMDLINE masks ttySAC0 from /sys/class/tty/
	# console/active, so systemd-getty-generator won't spawn one on its own.
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl enable serial-getty@ttySAC0.service
	# systemd-backlight@.service pulls felix into systemd "degraded" on every
	# boot; mask it (symlink to /dev/null) to keep `systemctl is-system-running`
	# green.
	$(NSPAWN) -D $(SYSROOT_DIR) \
		ln -sf /dev/null /etc/systemd/system/systemd-backlight@.service
	# Prefer NetworkManager over dhcpcd and pre-seed a DHCP ethernet profile.
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl disable dhcpcd
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl enable NetworkManager
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"nmcli --offline connection add type ethernet con-name default_connection ipv4.method auto autoconnect true \
		> /etc/NetworkManager/system-connections/default_connection.nmconnection"
	$(NSPAWN) -D $(SYSROOT_DIR) chmod 600 /etc/NetworkManager/system-connections/default_connection.nmconnection
	# Apply tracked overlay (usb_gadget, blacklist.conf, custom service, ...).
	sudo rsync -a $(OVERLAY_DIR)/ $(SYSROOT_DIR)/
	# Stamp the image version: os-release fields are read by agetty's \S{}
	# escape in /etc/issue (login banner); /etc/image-version is a standalone
	# discoverable copy. Must run inside nspawn — /etc/os-release is a symlink
	# into /usr/lib, which only resolves correctly within the container.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"echo 'IMAGE_VERSION=\"$(IMAGE_VERSION)\"' >> /etc/os-release; \
		echo 'IMAGE_BUILD_DATE=\"$(BUILD_DATE)\"' >> /etc/os-release; \
		printf '%s\n' '$(IMAGE_VERSION)' > /etc/image-version"
	just unmount_rootfs
	touch $@

.install_kernel: .build_kernel .install_packages
	just mount_rootfs
	sudo mkdir -p $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)
	sudo cp $(KERNEL_BUILD_DIR)/modules.builtin $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/
	sudo cp $(KERNEL_BUILD_DIR)/modules.builtin.modinfo $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/
	sudo rm -f $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order
	sudo touch $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order
	@echo "Copying modules"
	# Wipe stale .ko files from a previous kernel build before resyncing.
	# rsync below must overwrite, not skip — a previous build's modules have
	# __versions CRCs computed against the old vmlinux, so leaving them in
	# place causes every module to fail MODVERSIONS check against a freshly
	# rebuilt kernel and kicks the device into a watchdog reboot loop.
	sudo find $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION) -name '*.ko' -delete 2>/dev/null || true
	for staging in vendor_dlkm system_dlkm; \
	do \
		sudo mkdir -p rootfs/unpack/"$$staging" && \
		sudo tar \
			-xvzf $(KERNEL_BUILD_DIR)/"$$staging"_staging_archive.tar.gz \
			-C rootfs/unpack/"$$staging"; \
		sudo rsync -avK --include='*/' --include='*.ko' --exclude='*' rootfs/unpack/"$$staging"/ $(SYSROOT_DIR)/; \
		sudo sh -c "cat rootfs/unpack/\"$$staging\"/lib/modules/$(KERNEL_VERSION)/modules.order \
			>> $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order"; \
	done
	@echo "Updating System.map"
	sudo cp $(KERNEL_BUILD_DIR)/System.map $(SYSROOT_DIR)/boot/System.map-$(KERNEL_VERSION)
	@echo "Updating module dependencies"
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) depmod \
		--errsyms \
		--all \
		--filesyms /boot/System.map-$(KERNEL_VERSION) \
		$(KERNEL_VERSION)
	@echo "Copying kernel headers"
	sudo mkdir -p rootfs/unpack/kernel_headers
	sudo tar \
		-xvzf $(KERNEL_BUILD_DIR)/kernel-headers.tar.gz \
		-C rootfs/unpack/kernel_headers
	sudo cp -r rootfs/unpack/kernel_headers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)
	sudo ln -rsf $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION) $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/build
	sudo cp $(KERNEL_BUILD_DIR)/kernel_aarch64_Module.symvers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)/
	sudo cp $(KERNEL_BUILD_DIR)/vmlinux.symvers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)/
	@echo "Writing dracut force-drivers list"
	sudo rm -f $(MODULE_ORDER_PATH)
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/vendor_kernel_boot.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		> $(MODULE_ORDER_PATH)"
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/vendor_dlkm.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		>> $(MODULE_ORDER_PATH)"
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/system_dlkm.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		>> $(MODULE_ORDER_PATH)"
	# Strip blacklisted modules so dracut --force-drivers doesn't pull them
	# into the initramfs despite /etc/modprobe.d/blacklist.conf.
	sudo sed -i '/^bcmdhd4389$$/d; /^exynos_mfc$$/d' $(MODULE_ORDER_PATH)
	just unmount_rootfs
	touch $@

.install_initramfs: .install_kernel .install_packages .install_vendor_firmware
	just mount_rootfs
	# Bundle aoc.bin into the initramfs at the path firmware_class.path
	# (/vendor/firmware, set by the dtb's /chosen/bootargs) points at.
	# Without it, the AOC coprocessor retry-loops in dracut and starves
	# UART RX, so emergency-shell keystrokes are dropped.
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) dracut \
		--kver $(KERNEL_VERSION) \
		--lz4 \
		--show-modules \
		--force \
		--add "rescue bash" \
		--install /vendor/firmware/aoc.bin \
		--kernel-cmdline "rd.shell" \
		--force-drivers "$$(tr '\n' ' ' < $(MODULE_ORDER_PATH))"
	just unmount_rootfs
	touch $@

.build_boot: .install_initramfs .install_vendor_firmware
	$(MKBOOTIMG) \
		--kernel $(KERNEL_BUILD_DIR)/Image.lz4 \
		--cmdline "root=/dev/disk/by-partlabel/super" \
		--header_version 4 \
		-o boot/boot.img \
		--pagesize 2048 \
		--os_version 15.0.0 \
		--os_patch_level 2025-02
	just mount_rootfs
	sudo $(MKBOOTIMG) \
		--ramdisk_name "" \
		--vendor_ramdisk_fragment $(INITRAMFS_PATH) \
		--dtb $(KERNEL_BUILD_DIR)/dtb.img \
		--header_version 4 \
		--vendor_boot boot/vendor_boot.img \
		--pagesize 2048 \
		--os_version 15.0.0 \
		--os_patch_level 2025-02
	just unmount_rootfs
	touch $@

clean_image:
	just unmount_rootfs
	rm -f $(ROOTFS_IMG)
	rm -f .create_image .debootstrap .install_vendor_firmware .install_packages .install_kernel .install_initramfs .build_boot

clean: clean_image
	rm -f boot/boot.img boot/vendor_boot.img
	sudo rm -rf rootfs/unpack
