.PHONY: all clean clean_image stamp_version install_arm_blobs

# This Makefile is driven by the justfile; most variables come in via env.
# Targets with a leading "." are sentinel files that track whether a stage has
# completed successfully, so reruns skip already-finished work.

RELEASE ?= trixie
ROOT_PW ?= 0000
USER_LOGIN ?= kalm
USER_PW ?= 0000
HOSTNAME ?= fold
# kmscon isn't in trixie, so we fetch the arm64 .deb out of the Debian archive.
# The plain pool path (ftp.*/debian/pool/...) gets purged once a package is
# superseded, so we use snapshot.debian.org's permanent content-addressed
# /file/<sha1> URL and verify the download against KMSCON_SHA256, so a
# wrong/corrupt fetch fails the build instead of installing a surprise kmscon.
# The pin is (re)generated by `just update_snapshot` into rootfs/kmscon.env,
# included here; the ?= values are the committed fallback so a fresh checkout
# still builds if that file is absent.
-include rootfs/kmscon.env
KMSCON_URL ?= https://snapshot.debian.org/file/19dae225043718dfcbf02b50a7fcbedbfe4ab262
KMSCON_SHA256 ?= 5a200898513a82cac4f9262f7c20fe4b2bfc6d1d57045ab5f7d9ee0b9ca07a4f
# felix's super partition is 2082816 × 4096B = 8136.9 MiB; 8100M leaves a small
# margin so fastboot doesn't reject on a slightly-oversized image.
SIZE ?= 8100M
SYSROOT_DIR ?= rootfs/sysroot
KERNEL_SOURCE_DIR ?= kernel/source
KERNEL_BUILD_DIR ?= $(KERNEL_SOURCE_DIR)/out/felix/dist
APT_PACKAGES_FILE ?= rootfs/packages.txt

# Sysroot-relative paths retired from rootfs/overlay/. See the rm -f in
# .install_packages for why deleting an overlay file is not enough on its own.
RETIRED_OVERLAY_PATHS ?= \
	etc/systemd/system/multi-user.target.wants/netcheck-recover.service \
	etc/systemd/system/multi-user.target.wants/mark-slot-successful.service
MODULE_ORDER_PATH ?= rootfs/module_order.txt
ROOTFS_IMG ?= boot/rootfs.img
MKBOOTIMG ?= tools/mkbootimg/mkbootimg.py
BAZEL ?= kernel/source/tools/bazel
OVERLAY_DIR ?= rootfs/overlay
VENDOR_FIRMWARE_STAGE ?= rootfs/vendor-firmware/extracted

# ARM NDA GPU userland blobs (Mali Vulkan + OpenCL). Committed only as an
# age-encrypted, rootfs-rooted overlay tarball, encrypted to every pubkey in
# $(ARM_RECIPIENTS); tools/arm-blobs.sh decrypts (with the builder's own SSH
# key) and installs it. Not a recipient / no key / blob absent => warning, not a
# build failure. See secrets/README.md. ARM_NDA_KEY optionally pins a specific
# identity (private key) file; empty => fall back to the builder's ~/.ssh keys.
SECRETS_DIR ?= secrets
ARM_BLOBS_ENC ?= $(SECRETS_DIR)/arm-mali-blobs.tar.age
ARM_RECIPIENTS ?= $(SECRETS_DIR)/recipients.txt
ARM_NDA_KEY ?=
ARM_BLOBS_SCRIPT ?= tools/arm-blobs.sh

OVERLAY_FILES := $(shell find $(OVERLAY_DIR) -type f 2>/dev/null)

# Pre-built static aarch64-musl binary copied into the overlay tree by
# .build_pixel_bootctl. Source-of-truth lives in the tools/pixel-bootctl
# submodule (github.com/junkyard-computing/pixel-bootctl, the rescoped
# pixel-devinfo). Used by the mark-slot-successful systemd unit (via
# `pixel-bootctl mark-successful`) to clear the bootloader's slot retry
# counter so the device doesn't fall into fastboot after a few boots.
# Static musl => no dynamic loader / glibc dependency, so the binary runs
# unchanged on the Debian rootfs (a glibc cross-build baked a build-host
# ld-linux path and failed to exec on-device with 203/EXEC).
PIXEL_BOOTCTL_DIR ?= tools/pixel-bootctl
PIXEL_BOOTCTL_TARGET ?= aarch64-unknown-linux-musl
PIXEL_BOOTCTL_BIN ?= $(PIXEL_BOOTCTL_DIR)/target/$(PIXEL_BOOTCTL_TARGET)/release/pixel-bootctl
PIXEL_BOOTCTL_OVERLAY ?= $(OVERLAY_DIR)/usr/local/bin/pixel-bootctl
PIXEL_BOOTCTL_SOURCES := $(wildcard $(PIXEL_BOOTCTL_DIR)/Cargo.toml $(PIXEL_BOOTCTL_DIR)/Cargo.lock $(PIXEL_BOOTCTL_DIR)/src/*.rs)

# pixel-ota: same static aarch64-musl cross-build as pixel-bootctl (shares
# PIXEL_BOOTCTL_TARGET), installed into the overlay so every built image ships
# it. It used to be source-only — flash-ssh.sh required a manual cross-build —
# but it is an on-device tool (`pixel-ota update` / `flash-rootfs` run over SSH),
# so baking it into the rootfs is the same treatment pixel-bootctl gets. Source-
# of-truth is the tools/pixel-ota submodule.
PIXEL_OTA_DIR ?= tools/pixel-ota
PIXEL_OTA_BIN ?= $(PIXEL_OTA_DIR)/target/$(PIXEL_BOOTCTL_TARGET)/release/pixel-ota
PIXEL_OTA_OVERLAY ?= $(OVERLAY_DIR)/usr/local/bin/pixel-ota
PIXEL_OTA_SOURCES := $(wildcard $(PIXEL_OTA_DIR)/Cargo.toml $(PIXEL_OTA_DIR)/Cargo.lock $(PIXEL_OTA_DIR)/src/*.rs)

# Debian archive pin. rootfs/debian_snapshot holds a snapshot.debian.org
# timestamp (managed by `just update_snapshot`); pinning the mirror is what
# makes a given IMAGE_VERSION reproducible. An empty pin leaves MIRROR empty,
# so debootstrap falls back to its default (live) mirror — a fresh checkout
# without a pin still builds.
SNAPSHOT ?= $(shell cat rootfs/debian_snapshot 2>/dev/null)
MIRROR ?= $(if $(SNAPSHOT),https://snapshot.debian.org/archive/debian/$(SNAPSHOT)/,)

# Image version string for /etc/os-release + the login banner. version.txt holds
# the human-bumped number (managed by release-please); the git short hash (and
# -dirty marker) pin it to a build. BUILD_DATE is informational — the snapshot
# pin above is the actual reproducibility anchor, not the build date.
#
# The kernel version is folded in (+k<ver>) because experiments here vary the
# KERNEL, and the stamp's whole job is to let two phones be told apart by what
# they actually run. A commit-only stamp can't distinguish two kernel variants
# built from the same tree state; binding the kernel string closes that.
#
# Provenance is RECOMPUTED, NEVER CACHED: the stamp is a *description of the
# result*, not a build stage. It is written by the PHONY `stamp_version` target
# (no sentinel; `just all` runs it after .build_boot) so it re-runs on every
# build and can never go stale relative to the kernel/commit/tree — the failure
# that previously let kernel changes ship under an old version string.
IMAGE_BASE_VERSION := $(shell cat version.txt 2>/dev/null || echo 0.0.0)
GIT_REV := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
GIT_DIRTY := $(shell test -n "$$(git status --porcelain 2>/dev/null)" && echo -dirty)
IMAGE_VERSION ?= $(IMAGE_BASE_VERSION)-g$(GIT_REV)$(GIT_DIRTY)$(if $(KERNEL_VERSION),+k$(KERNEL_VERSION),)
BUILD_DATE ?= $(shell date -u +%Y-%m-%d)

# Wrap nspawn invocations through tools/nspawn-wrap.sh so each one starts
# from a known-good sysroot/dev (no leftover mounts, no stale /dev/pts).
# See the script header for the systemd >= 260 specifics that motivate it.
# Trailing `--` separates the wrapper's sysroot arg from the nspawn argv.
NSPAWN_WRAP := sudo tools/nspawn-wrap.sh $(SYSROOT_DIR) --
# --resolv-conf=bind-host overrides the container's /etc/resolv.conf for the
# lifetime of the nspawn session. Packages.txt installs systemd-resolved,
# whose postinst points /etc/resolv.conf at a stub that only resolves when
# systemd-resolved is running (it isn't, under nspawn). Without this flag,
# any nspawn call after that postinst loses DNS, including reruns.
NSPAWN := $(NSPAWN_WRAP) --resolv-conf=bind-host

# Running `make` directly bypasses the env vars set by the justfile (notably
# KERNEL_VERSION, which is read from kernel/kernel_version). Always go through
# `just all` so those are in scope.
all:
	@echo "Use 'just all' instead so KERNEL_VERSION and friends are exported."
	@just --list

.create_image:
	mkdir -p $(SYSROOT_DIR)
	# Use truncate, not fallocate: truncate makes a sparse file (8100M nominal but
	# only the written blocks occupy host disk; `just trim_rootfs` keeps it that
	# way), whereas fallocate would reserve the full size upfront. Sparse is fine
	# for mkfs.ext4 + fastboot.
	sudo truncate -s $(SIZE) $(ROOTFS_IMG)
	sudo mkfs.ext4 -F -L rootfs $(ROOTFS_IMG)
	touch $@

.debootstrap: .create_image
	just mount_rootfs
	# Trailing $(MIRROR) pins the archive to the snapshot.debian.org timestamp
	# in rootfs/debian_snapshot; empty MIRROR => debootstrap's default mirror.
	# --components: debootstrap defaults to `main` only, and writes the
	# components it actually fetched into the sysroot's /etc/apt/sources.list.
	# firmware-realtek (the r8152 dongle's errata patch — mandatory, see the
	# network section of CLAUDE.md) ships in non-free-firmware, so it has to be
	# enabled here or apt reports "no installation candidate".
	sudo debootstrap --variant=minbase --components=main,non-free-firmware --include=symlinks --arch=arm64 --foreign $(RELEASE) $(SYSROOT_DIR) $(MIRROR)
	# nixpkgs heavily patches debootstrap: both the shebang AND in-script
	# references to dpkg/chroot/unshare are rewritten to absolute /nix/store
	# paths. --foreign copies the host script verbatim into sysroot, so
	# inside the nspawn container those paths don't exist and the script
	# either fails to exec or silently dies on `set -e` when the first
	# nix-store binary is invoked. Rewrite both:
	#   - line 1 (shebang): /nix/store/<hash>/bin/bash → /bin/bash
	#   - lines 2..: strip /nix/store/<hash>/bin/ entirely so PATH lookup
	#     resolves the (container's own) dpkg, chroot (/usr/sbin), unshare.
	# No-op on non-Nix hosts (the upstream debootstrap has no /nix/store
	# references at all).
	sudo sed -i \
		-e '1s|^#!/nix/store/[^/]*/bin/|#!/bin/|' \
		-e '2,$$s|/nix/store/[^/]*/bin/||g' \
		$(SYSROOT_DIR)/debootstrap/debootstrap
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) debootstrap/debootstrap --second-stage
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) symlinks -cr .
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) sh -c "echo root:$(ROOT_PW) | chpasswd"
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) sh -c "echo $(HOSTNAME) > /etc/hostname"
	just unmount_rootfs
	touch $@

# Must build inside the flake's FHS shell so kleaf's host tools (python3, perl, bash,
# rsync) resolve and Bazel's server starts in the FHS mount namespace:
#   nix run .#bazel-fhs -- -c 'just build_kernel'
# --config=local is kleaf's "reduce sandboxes" mode (build/kernel/kleaf/docs/sandbox.md):
# it runs the in-tree kernel_build/kernel_config actions locally (per-target cache dirs)
# while keeping modules_install/dtbo/uapi/abi actions sandboxed. This is what makes
# --config=use_source_tree_aosp (in-tree GKI build) work on NixOS. Do NOT replace it with
# a blanket --spawn_strategy=local: that forces the sandbox-required actions to run local
# and they abort with "FATAL: this action must be executed in a sandbox!".
# NOTE: per the kleaf docs, run `tools/bazel clean` if you change --strategy/--config,
# else stale cached action outputs cause confusing failures.
.build_kernel: kernel/custom_defconfig_mod/BUILD.bazel kernel/custom_defconfig_mod/custom_defconfig
	cd $(KERNEL_SOURCE_DIR); $(BAZEL) run \
		--config=use_source_tree_aosp \
		--config=stamp \
		--config=felix \
		--config=local \
		--defconfig_fragment=//custom_defconfig_mod:custom_defconfig \
		//private/devices/google/felix:gs201_felix_dist
	@echo "Updating kernel version string"
	strings $(KERNEL_BUILD_DIR)/Image | grep "Linux version" | head -n 1 | awk '{print $$3}' > kernel/kernel_version
	touch $@

.sync_vendor_firmware:
	just sync_vendor_firmware
	touch $@

.install_vendor_firmware: .debootstrap .sync_vendor_firmware
	just mount_rootfs
	sudo mkdir -p $(SYSROOT_DIR)/vendor/firmware
	# --chown=root:root for the same reason as the overlay rsync: the extracted
	# staging tree is owned by the build user (uid 1000 = $(USER_LOGIN) on the
	# device), and `rsync -a` preserves that. Without it the unprivileged user
	# owns /vendor/firmware and everything in it — including aoc.bin, which the
	# firmware loader reads and without which the device does not boot.
	sudo rsync -a --chown=root:root $(VENDOR_FIRMWARE_STAGE)/firmware/ $(SYSROOT_DIR)/vendor/firmware/
	just unmount_rootfs
	touch $@

# Cross-compile pixel-bootctl to a fully static aarch64-musl binary and copy it
# into the overlay tree. Links with the Rust toolchain's bundled rust-lld and
# strips via rustc (-C strip), so no external aarch64 gcc/strip is needed — the
# same recipe works in the flake's devShell and on any non-Nix host that has
# rustup's aarch64-unknown-linux-musl target installed. Static => no dynamic
# loader, so it runs unchanged on the Debian rootfs.
.build_pixel_bootctl: $(PIXEL_BOOTCTL_SOURCES)
	cd $(PIXEL_BOOTCTL_DIR) && \
		RUSTFLAGS="-C linker=rust-lld -C strip=symbols" \
		cargo build --release --target $(PIXEL_BOOTCTL_TARGET)
	mkdir -p $(dir $(PIXEL_BOOTCTL_OVERLAY))
	install -m 0755 $(PIXEL_BOOTCTL_BIN) $(PIXEL_BOOTCTL_OVERLAY)
	touch $@

# pixel-ota: identical cross-build recipe to pixel-bootctl (see the comment
# above .build_pixel_bootctl for the static-musl rationale).
.build_pixel_ota: $(PIXEL_OTA_SOURCES)
	cd $(PIXEL_OTA_DIR) && \
		RUSTFLAGS="-C linker=rust-lld -C strip=symbols" \
		cargo build --release --target $(PIXEL_BOOTCTL_TARGET)
	mkdir -p $(dir $(PIXEL_OTA_OVERLAY))
	install -m 0755 $(PIXEL_OTA_BIN) $(PIXEL_OTA_OVERLAY)
	touch $@

.install_packages: .debootstrap .build_pixel_bootctl .build_pixel_ota $(APT_PACKAGES_FILE) $(OVERLAY_FILES) version.txt
	just mount_rootfs
	# apt tuning for the snapshot.debian.org mirror (all harmless on the live
	# mirror, so written unconditionally):
	#   Check-Valid-Until false  - snapshot Release files carry an old
	#                              Valid-Until; apt rejects them as expired.
	#   Retries 5                - snapshot intermittently freezes a connection
	#     + *::Timeout 60          mid-transfer; without a timeout apt hangs
	#                              forever, so cap it and retry instead.
	#   Pipeline-Depth 0         - snapshot throttles/stalls under apt's default
	#                              HTTP pipelining; disable it.
	# Regular file, no symlink — safe to write host-side into the mounted sysroot.
	sudo sh -c "printf '%s\n' \
		'Acquire::Check-Valid-Until \"false\";' \
		'Acquire::Retries \"5\";' \
		'Acquire::http::Timeout \"60\";' \
		'Acquire::https::Timeout \"60\";' \
		'Acquire::http::Pipeline-Depth \"0\";' \
		> $(SYSROOT_DIR)/etc/apt/apt.conf.d/99snapshot"
	# Ensure the non-free-firmware component is enabled before `apt-get update`,
	# so firmware-realtek resolves. .debootstrap now passes --components for
	# this, but editing that recipe does NOT invalidate its sentinel — an
	# already-debootstrapped sysroot would still carry a main-only sources.list
	# and fail here. Idempotent, so it is a no-op once the component is present.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"grep -q non-free-firmware /etc/apt/sources.list \
		|| sed -i '/^deb .* main/ s/$$/ non-free-firmware/' /etc/apt/sources.list"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c "apt-get update"
	# Locale setup.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"DEBIAN_FRONTEND=noninteractive apt-get -y install locales apt-utils"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"export DEBIAN_FRONTEND=noninteractive; \
		sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
		&& dpkg-reconfigure locales \
		&& update-locale en_US.UTF-8"
	# Pre-stage the pinned kmscon .deb (trixie dropped the package) so the
	# single apt-get install below resolves its deps alongside packages.txt.
	sudo curl -L --fail -o $(SYSROOT_DIR)/var/cache/apt/archives/kmscon.deb "$(KMSCON_URL)"
	# Fail loudly if the fetched .deb isn't the pinned one.
	echo "$(KMSCON_SHA256)  $(SYSROOT_DIR)/var/cache/apt/archives/kmscon.deb" | sha256sum -c -
	# Packages from rootfs/packages.txt plus the staged kmscon .deb.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"DEBIAN_FRONTEND=noninteractive apt-get -y install $(APT_PACKAGES) /var/cache/apt/archives/kmscon.deb"
	# Drop the downloaded .deb cache so it doesn't accumulate in the image across
	# rebuilds — it otherwise grows every time the snapshot pin / package set
	# changes (new versions fetched, old ones never purged).
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c "apt-get clean"
	# Unprivileged user with passwordless sudo. Paired with the autologin
	# override in rootfs/overlay/etc/systemd/system/kmsconvt@.service.d/.
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"id -u $(USER_LOGIN) >/dev/null 2>&1 || useradd -m -s /bin/bash -G sudo $(USER_LOGIN)"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"echo $(USER_LOGIN):$(USER_PW) | chpasswd"
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"echo '%sudo ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/99-sudo-nopasswd \
		&& chmod 0440 /etc/sudoers.d/99-sudo-nopasswd"
	# Explicitly enable a getty on felix's UART console. The compiled-in
	# `console=ttynull` in CONFIG_CMDLINE masks ttySAC0 from /sys/class/tty/
	# console/active, so systemd-getty-generator won't spawn one on its own.
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl enable serial-getty@ttySAC0.service
	# systemd-backlight@.service pulls felix into systemd "degraded" on every
	# boot; mask it (symlink to /dev/null) to keep `systemctl is-system-running`
	# green.
	$(NSPAWN) -D $(SYSROOT_DIR) \
		ln -sf /dev/null /etc/systemd/system/systemd-backlight@.service
	# Prefer NetworkManager over dhcpcd and pre-seed a DHCP ethernet profile.
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl disable dhcpcd
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl enable NetworkManager
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"nmcli --offline connection add type ethernet con-name default_connection ipv4.method auto autoconnect true \
		> /etc/NetworkManager/system-connections/default_connection.nmconnection"
	$(NSPAWN) -D $(SYSROOT_DIR) chmod 600 /etc/NetworkManager/system-connections/default_connection.nmconnection
	# Apply tracked overlay (usb_gadget, blacklist.conf, custom service, ...).
	# Units are enabled by the .wants symlinks committed under the overlay's
	# etc/systemd/system/, not by `systemctl enable` here.
	# --chown=root:root is REQUIRED. `rsync -a` preserves SOURCE ownership, and
	# rootfs/overlay/ is owned by the build user (uid 1000 here) — which is the
	# same uid as $(USER_LOGIN) on the device. Without this, every directory the
	# overlay touches lands owned by that unprivileged user, including `/`,
	# /etc, /usr, /etc/systemd/system, /etc/udev/rules.d and /usr/local/sbin.
	#
	# That is a privilege hole on its own, and it also silently breaks
	# systemd-tmpfiles: it refuses to traverse an unprivileged-owned directory
	# into a root-owned one ("Detected unsafe path transition / (owned by kalm)
	# → /sys ..."), so tmpfiles.d entries under /sys are skipped with no error.
	# That is how the USB-autosuspend fix appeared to apply and did nothing.
	sudo rsync -a --chown=root:root $(OVERLAY_DIR)/ $(SYSROOT_DIR)/
	# ...and repair the ancestors. --chown only takes effect on entries rsync
	# actually rewrites, so leaf dirs whose contents changed get fixed while
	# untouched parents keep whatever ownership a previous (pre---chown) build
	# gave them. Measured: /etc/systemd/system and /usr/local/sbin came out
	# uid=0 while `/`, /etc and /usr stayed uid=1000 — and `/` is exactly the
	# one that makes systemd-tmpfiles refuse to work. Chown every directory the
	# overlay contains, plus the sysroot root itself. Scoped to overlay dirs on
	# purpose: a blanket chown -R would clobber /home/$(USER_LOGIN).
	# Built with -printf rather than `-exec chown ... {} +`: GNU find requires a
	# lone {} in the + form, so embedding it in a longer path is a hard error
	# ("the '{}' must appear by itself"). abspath also keeps this correct
	# whether SYSROOT_DIR arrives relative or already absolute — the justfile
	# passes it absolute, so an added $(CURDIR)/ prefix yielded /work//work/...
	sudo chown root:root $(SYSROOT_DIR)
	cd $(OVERLAY_DIR) && find . -type d -printf '$(abspath $(SYSROOT_DIR))/%P\0' \
		| sudo xargs -0 --no-run-if-empty chown root:root
	# RETIRED_OVERLAY_PATHS — files that USED to ship in the overlay and must be
	# actively removed from the sysroot.
	#
	# The rsync above is deliberately NOT --delete: the overlay is a sparse graft
	# onto a full Debian install, so --delete would try to remove the entire
	# distro. The consequence is that `git rm`-ing an overlay file does NOT
	# remove it from the image — .debootstrap's sentinel means the sysroot is
	# never wiped between builds, so the stale copy survives every rebuild and
	# keeps shipping. A deleted unit therefore stays ENABLED on device.
	#
	# So retiring an overlay file is two steps: delete it from the overlay AND
	# list it here. Entries can be dropped once .debootstrap has been rerun for
	# other reasons (a wiped sysroot never had them).
	sudo rm -f $(addprefix $(SYSROOT_DIR)/,$(RETIRED_OVERLAY_PATHS))
	# pstore-beacon (overlay) surfaces the PREVIOUS boot's panic dmesg on UART —
	# felix has one USB-C port, so we usually can't be UART-attached for the boot
	# that crashes. systemd-pstore.service would race it for the records, so mask
	# it: the beacon is the single owner of /sys/fs/pstore consumption.
	$(NSPAWN) -D $(SYSROOT_DIR) \
		ln -sf /dev/null /etc/systemd/system/systemd-pstore.service
	# dnsmasq is installed ONLY to serve DHCP on the USB gadget link, started
	# ad-hoc by usr/local/sbin/usb_gadget bound to usb0. Debian enables
	# dnsmasq.service on install, and that system-wide instance binds the
	# wildcard address — on a lab/fleet LAN that is a rogue DHCP server handing
	# leases to everything on the wire. Disable it; the gadget script's
	# --bind-interfaces instance is the only one that should ever run.
	$(NSPAWN) -D $(SYSROOT_DIR) systemctl disable dnsmasq.service || true
	# NOTE: the image-version stamp used to live here — moved to the PHONY
	# `stamp_version` target (run by `just all` after .build_boot) so it is
	# recomputed every build and reflects the actual kernel, not whatever was
	# stamped the first time this (sentinel-gated) stage ran. See IMAGE_VERSION.
	just unmount_rootfs
	touch $@

.install_kernel: .build_kernel .install_packages
	just mount_rootfs
	sudo mkdir -p $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)
	sudo cp $(KERNEL_BUILD_DIR)/modules.builtin $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/
	sudo cp $(KERNEL_BUILD_DIR)/modules.builtin.modinfo $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/
	sudo rm -f $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order
	sudo touch $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order
	@echo "Copying modules"
	# Wipe stale .ko files from a previous kernel build before resyncing.
	# rsync below must overwrite, not skip — a previous build's modules have
	# __versions CRCs computed against the old vmlinux, so leaving them in
	# place causes every module to fail MODVERSIONS check against a freshly
	# rebuilt kernel and kicks the device into a watchdog reboot loop.
	sudo find $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION) -name '*.ko' -delete 2>/dev/null || true
	for staging in vendor_dlkm system_dlkm; \
	do \
		sudo mkdir -p rootfs/unpack/"$$staging" && \
		sudo tar \
			-xvzf $(KERNEL_BUILD_DIR)/"$$staging"_staging_archive.tar.gz \
			-C rootfs/unpack/"$$staging"; \
		sudo rsync -avK --include='*/' --include='*.ko' --exclude='*' rootfs/unpack/"$$staging"/ $(SYSROOT_DIR)/; \
		sudo sh -c "cat rootfs/unpack/\"$$staging\"/lib/modules/$(KERNEL_VERSION)/modules.order \
			>> $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/modules.order"; \
	done
	@echo "Updating System.map"
	sudo cp $(KERNEL_BUILD_DIR)/System.map $(SYSROOT_DIR)/boot/System.map-$(KERNEL_VERSION)
	@echo "Updating module dependencies"
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) depmod \
		--errsyms \
		--all \
		--filesyms /boot/System.map-$(KERNEL_VERSION) \
		$(KERNEL_VERSION)
	@echo "Copying kernel headers"
	sudo mkdir -p rootfs/unpack/kernel_headers
	sudo tar \
		-xvzf $(KERNEL_BUILD_DIR)/kernel-headers.tar.gz \
		-C rootfs/unpack/kernel_headers
	sudo cp -r rootfs/unpack/kernel_headers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)
	sudo ln -rsf $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION) $(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/build
	sudo cp $(KERNEL_BUILD_DIR)/kernel_aarch64_Module.symvers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)/
	sudo cp $(KERNEL_BUILD_DIR)/vmlinux.symvers $(SYSROOT_DIR)/usr/src/linux-headers-$(KERNEL_VERSION)/
	@echo "Writing dracut force-drivers list"
	sudo rm -f $(MODULE_ORDER_PATH)
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/vendor_kernel_boot.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		> $(MODULE_ORDER_PATH)"
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/vendor_dlkm.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		>> $(MODULE_ORDER_PATH)"
	sudo sh -c "cat $(KERNEL_BUILD_DIR)/system_dlkm.modules.load | xargs -I {} \
		modinfo -b $(SYSROOT_DIR) -k $(KERNEL_VERSION) -F name \"$(SYSROOT_DIR)/lib/modules/$(KERNEL_VERSION)/{}\" \
		>> $(MODULE_ORDER_PATH)"
	# Strip blacklisted modules so dracut --force-drivers doesn't pull them
	# into the initramfs despite /etc/modprobe.d/blacklist.conf.
	sudo sed -i '/^bcmdhd4389$$/d; /^exynos_mfc$$/d' $(MODULE_ORDER_PATH)
	# Prune module/header/boot trees from other kernel versions so a
	# KERNEL_VERSION bump doesn't accumulate stale ones in the image. (The new
	# version's initrd is (re)created later in .install_initramfs.)
	sudo find $(SYSROOT_DIR)/lib/modules -mindepth 1 -maxdepth 1 -type d \
		! -name '$(KERNEL_VERSION)' -exec rm -rf {} +
	sudo find $(SYSROOT_DIR)/usr/src -mindepth 1 -maxdepth 1 -type d \
		-name 'linux-headers-*' ! -name 'linux-headers-$(KERNEL_VERSION)' -exec rm -rf {} +
	sudo find $(SYSROOT_DIR)/boot -mindepth 1 -maxdepth 1 \
		\( -name 'initrd.img-*' -o -name 'System.map-*' \) \
		! -name '*-$(KERNEL_VERSION)' -exec rm -f {} +
	just unmount_rootfs
	touch $@

.install_initramfs: .install_kernel .install_packages .install_vendor_firmware
	just mount_rootfs
	# Bundle aoc.bin into the initramfs at the path firmware_class.path
	# (/vendor/firmware, set by the dtb's /chosen/bootargs) points at.
	# Without it, the AOC coprocessor retry-loops in dracut and starves
	# UART RX, so emergency-shell keystrokes are dropped.
	#
	# rd.shell=0 rd.emergency=reboot: a dracut failure must REBOOT, never wait
	# at an interactive shell. The shipped configuration has no screen, no
	# volume keys and no power button, and the initramfs has no networking, so
	# an emergency shell is reachable only by someone physically attaching a
	# UART adapter — which on a fielded unit is nobody. Worse, it is reachable
	# only in theory even on the bench: the one time dracut actually did fail
	# here (missing aoc.bin, no /dev/disk/by-partlabel/super) it dropped to an
	# emergency shell that could not be typed into, because the AOC retry loop
	# was starving UART RX. So the shell buys nothing and costs everything: a
	# hang is permanent, whereas a reboot burns a slot-retry and lets the
	# bootloader roll back to the other slot. Panics already self-recover
	# (CONFIG_PANIC_TIMEOUT=-1, CONFIG_PANIC_ON_OOPS=y); this closes the
	# non-panic hang path.
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) dracut \
		--kver $(KERNEL_VERSION) \
		--lz4 \
		--show-modules \
		--force \
		--add "rescue bash rootfs-flash" \
		--install /vendor/firmware/aoc.bin \
		--kernel-cmdline "rd.shell=0 rd.emergency=reboot" \
		--force-drivers "$$(tr '\n' ' ' < $(MODULE_ORDER_PATH))"
	just unmount_rootfs
	touch $@

# Always-run provenance stamp (PHONY, no sentinel) — see IMAGE_VERSION comment.
# Writes /etc/os-release IMAGE_VERSION/IMAGE_BUILD_DATE + /etc/image-version into
# the (already-built) rootfs. Runs inside nspawn because /etc/os-release is a
# symlink into /usr/lib that only resolves in the container. Idempotent: strips
# prior IMAGE_* lines before re-appending, so re-stamping never accumulates.
# Depends only on the rootfs existing (.install_packages), but is itself PHONY so
# it re-executes on every build regardless of sentinels.
stamp_version: .install_packages
	just mount_rootfs
	$(NSPAWN) -D $(SYSROOT_DIR) sh -c \
		"sed -i --follow-symlinks '/^IMAGE_VERSION=/d; /^IMAGE_BUILD_DATE=/d' /etc/os-release; \
		echo 'IMAGE_VERSION=\"$(IMAGE_VERSION)\"' >> /etc/os-release; \
		echo 'IMAGE_BUILD_DATE=\"$(BUILD_DATE)\"' >> /etc/os-release; \
		printf '%s\n' '$(IMAGE_VERSION)' > /etc/image-version"
	just unmount_rootfs
	@echo "stamped IMAGE_VERSION=$(IMAGE_VERSION)"

# Decrypt + install the ARM NDA GPU userland blobs into the rootfs. PHONY (no
# sentinel), like stamp_version: it re-runs every build so a builder who fixes
# their key (or gets added as a recipient + re-pulls the blob) picks the drivers
# up on the next `just all` with nothing to remember. tools/arm-blobs.sh exits 0
# when the blob/key is absent or the builder isn't a recipient, so this NEVER
# fails the build — it just warns and skips. Decoupled from .build_boot because
# the blobs land in rootfs.img (flashed to super), not in boot/vendor_boot.img;
# `just all` runs this after .build_boot. ldconfig refreshes the loader cache so
# a freshly-installed .so is found at runtime.
install_arm_blobs: .install_packages
	just mount_rootfs
	SECRETS_DIR=$(SECRETS_DIR) ARM_BLOBS_ENC=$(ARM_BLOBS_ENC) \
		ARM_RECIPIENTS=$(ARM_RECIPIENTS) ARM_NDA_KEY=$(ARM_NDA_KEY) \
		$(ARM_BLOBS_SCRIPT) install $(SYSROOT_DIR)
	$(NSPAWN_WRAP) -D $(SYSROOT_DIR) ldconfig || true
	just unmount_rootfs

.build_boot: .install_initramfs .install_vendor_firmware
	$(MKBOOTIMG) \
		--kernel $(KERNEL_BUILD_DIR)/Image.lz4 \
		--cmdline "root=/dev/disk/by-partlabel/super" \
		--header_version 4 \
		-o boot/boot.img \
		--pagesize 2048 \
		--os_version 15.0.0 \
		--os_patch_level 2025-02
	just mount_rootfs
	sudo $(MKBOOTIMG) \
		--ramdisk_name "" \
		--vendor_ramdisk_fragment $(INITRAMFS_PATH) \
		--dtb $(KERNEL_BUILD_DIR)/dtb.img \
		--header_version 4 \
		--vendor_boot boot/vendor_boot.img \
		--pagesize 2048 \
		--os_version 15.0.0 \
		--os_patch_level 2025-02
	just unmount_rootfs
	touch $@

clean_image:
	just unmount_rootfs
	rm -f $(ROOTFS_IMG)
	rm -f .create_image .debootstrap .install_vendor_firmware .install_packages .install_kernel .install_initramfs .build_boot

clean: clean_image
	rm -f boot/boot.img boot/vendor_boot.img
	sudo rm -rf rootfs/unpack
